#include <linux/ioctl.h>
#define IOC_MAGIC 'k'
#define IOCTL_SOBELCHUNKSX _IOW(IOC_MAGIC,'c',uint32_t*)
#define IOCTL_SOBELRESY _IOW(IOC_MAGIC,'y',uint32_t*)
#define IOCTL_SOBELKERNEL _IOW(IOC_MAGIC,'k',uint32_t*)
#define IOCTL_SOBELDMAMALLOC _IO(IOC_MAGIC,'m')
#define IOCTL_SOBELINPUTDATA _IOW(IOC_MAGIC,'i',uint8_t*)
#define IOCTL_SOBELEXECCMD _IO(IOC_MAGIC,'e')
#define IOCTL_SOBELWAIT _IO(IOC_MAGIC,'w')
#define IOCTL_SOBELOUTPUTDATA _IOR(IOC_MAGIC,'o',uint8_t*)
#define IOCTL_SOBELDMAFREE _IO(IOC_MAGIC,'f')
#define IOCTL_SOBELSTATUS _IOR(IOC_MAGIC,'s',uint32_t*)
